### ISSUE TITLE
Fail scan action

### ISSUE THREAD

**Issue by hyeongguen-song** [ShiftLeftSecurity/scan-action#30]
This error suddenly occurred while running github action. 
What is the problem?
Any help would be appreciated

- yml file
```yml
NextGen-Static-Analysis:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Perform Scan
      uses: ShiftLeftSecurity/scan-action@master
      env:
        WORKSPACE: ""
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SCAN_AUTO_BUILD: true
      with:
        output: reports
```
- traceback
> Traceback (most recent call last):
  File "/usr/local/src/scan", line 35, in <module>
    import lib.convert as convertLib
  File "/usr/local/src/lib/convert.py", line 28, in <module>
    from reporter.sarif import render_html
  File "/usr/local/lib/python3.8/site-packages/reporter/sarif.py", line 6, in <module>
    from jinja2 import Environment, Markup, PackageLoader, exceptions, select_autoescape
ImportError: cannot import name 'Markup' from 'jinja2' (/usr/local/lib/python3.8/site-packages/jinja2/__init__.py)
